/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {

    public static void main(String[] args) {
        /*
        ProjectController projectController = new ProjectController();
        
        Projects project = new Projects();
        project.setName("Projeto teste");
        project.setDescription("description");
        projectController.save(project);
        */
        
        // criando conexão
        
        
//        ProjectController projectController = new ProjectController();
//        
//        Project project = new Project();
//        project.setName("Projeto teste");
//        project.setDescription("description");
//        projectController.save(project);
//        
        
        ProjectController projectController = new ProjectController();
        
        Project project = new Project();
        project.setId(5);
        project.setName("Novo nome do projeto");
        project.setDescription("description");
        
        
        projectController.update(project);
  
        projectController.removeById(5);
        /*\
        
        ver total de projetos
        List<Projects> projects = projectController.getAll();
        System.out.println("Total de projetos = " + projects.size());
        */
        
//        TaskController taskController = new TaskController();
//        
//        Task task = new Task();
//        task.setIdProject(2);
//        task.setName("Criar as telas da aplicação");
//        task.setDescription("Devem ser criadas telas para os cadastros");
//        task.setNotes("Sem notas");
//        task.setIsCompleted(false);
//        task.setDeadLine(new Date());
//        
//        taskController.save(task);
//        
//        task.setName("Alterar telas da aplicação");
//        taskController.update(task);
//        List<Task> tasks = taskController.getAll(0);
//        System.out.println("Total de tarefas = " + tasks.size());
//        
        
 
    }
}
